import enums from "./enums.js";

export default {
    width: null,
    height: null,
    tickrate: 15,
    voronoi: null,
    cells: null,
    circumcenters : null,
    epsilon: 15,
    iselElevatingActive:true,
    
    mouseX: null,
    mouseY: null,
    canvas: null,
    context: null,
    context2: null,
    namesdiv: null,
    citiesdiv:null,
    namesbase : null,   
    mapmarkercontext : null,
    guicontext : null,
    circleRadius: 50,
    defaultColor : 'rgb(0,105,148)',
    shallowColor : 'rgb(83,156,202)',
    riverLevel :  30,
    map : {},
    PoI : {},
    names : {},
    Latitude : 30,
    mapsize : 0.2,
    dryness : 10,
    Elevationtype : enums.ELEVATIONTYPE.MOUNTAIN,
    menu : enums.MENU.ELEVATION,
    Biometype: enums.BIOMES.FOREST,
    Politicaltype : enums.POLITICALTYPE.ADDCITY,
    riversGenerated : false,
    biomesGenerated : false,
    TownsGenerated : false,
    CountriesGenerated : false,
    NameChangeId:0,
    NameChanger :null,
    cities:null,
    capitals:null,
    cityDivs : {},
    cityId :1,
    
}